[platformio]
build_dir = C:/Users/steve/.pio-build/ws2000-blink-test
libdeps_dir = C:/Users/steve/.pio-libdeps/ws2000-blink-test

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM8
monitor_port = COM8
upload_speed = 115200
monitor_speed = 115200
build_flags =
  -D LED_PIN=2
  -D WIFI_SSID=\"ukphotoguy\"
  -D WIFI_PASS=\"shrewsbury\"
